import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./Components/Navbar";
import { hind_madurai, ovo, poppins } from "./fonts";
import { Toaster } from "react-hot-toast";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` bg-background`}>
      
      <body
        className={`antialiased`}
      >
        <Toaster position="top-right"/>
        <Navbar/>

        <main className={`${ovo.variable} ${poppins.variable} ${hind_madurai.variable}`}>{children}</main>
      </body>
    </html>
  );
}
